image: julia:0.6

default:
  script: 
    - julia -e "Pkg.update();Pkg.clone(\"https://gitlab.com/Samantha.ai/Samantha.jl\");Pkg.checkout(\"Samantha\", \"\$(ENV[\"CI_COMMIT_REF_NAME\"])\");Pkg.test(\"Samantha\")"
